apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: tienda
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: __ECR_REGISTRY__/__ECR_DB_REPO__:latest
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tienda-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: tienda-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: tienda-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tienda-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/mysql
      volumes:
        - name: dbdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: tienda
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
