name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: ["main"]
    paths:
      - "db/**"
  workflow_dispatch:

env:
  ECR_REPOSITORY: ${{ vars.ENVIRONMENT }}-${{ vars.PROJECT_NAME }}-db-repo
  CLUSTER_NAME: ${{ vars.ENVIRONMENT }}-${{ vars.PROJECT_NAME }}-eks

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag y push a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd db
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
          docker tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

      - name: Configurar kubectl
        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Actualizar imagen en deployment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          kubectl set image deployment/db \
            db=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            -n tienda

      - name: Verificar rollout
        run: kubectl rollout status deployment/db -n tienda --timeout=120s
